matrix:
  include:
  - os: osx
    osx_image: xcode9.4
    language: node_js
    node_js: '10'
    env:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
deploy:
  provider: releases
  api_key:
    secure: RCN4LboCNOmiIgbnYTkotnMEBQFy1GU7H7ROQ9KNGOF66Y8h0o5wKfyCE5F7dY0g6ZyfoPJ88Jp81UmuDc+B3AeioST5kKQM0cG+RRvzbk0WO/Zf58y95ALasVegEA07hG4C6ORAwAwPc9CrSvRsdIQqDzWsOyqCNIiR/KWz7DB6htTfm9KHpC3p44TKNIci6+FZZo7CKmGLNEtDrr1e+tJtDmvPQQSDS7NGU2zMQOQX3dwrQyhOz+hL+VL1PuI9VWtNBqEFRh2Y4z00lB9gU4LSIbUGK2aof2bW0DG1BG1WjHWUAdtRH5GJdvBYqyLUN5HX60AaCwGfVjGwbrspchQv4cy2XkYezTMC5kVS6TPVIOhqhOOmztJesfkCKgDWgeo8xDM+zFwcYWQA2Nj5T9HW2IaU/HBAg/igFWo8d+r+h8KS5Jg/7gchWWrj3viZlpJeFz+qAJkrpx+lHDxl4T6yl5dVgkDS1U4vXBJlrH1TQMXcMGjbQb/ipS0a0QS4kicdQPWXoiFUnqQ4mCrNOPO0bDmkHm4AOWFlqMxwvP4YWmWe+1vOuaA/RiPs+YX1e721PAs9jLe1p5/CVHm0MukgtGqrrjB4++sd6uAYCUYm6odR4kfss1P16aRobWo2NfeKxl1ia4dUY0X/fQZ7kcHettR1OuBPrvXwHpyi4v0=
  file: ".travis.yml"
  on:
    repo: paulinem15/uhoo_app
cache:
  directories:
  - node_modules
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run dist-mac; fi
before_cache:
- rm -rf $HOME/.cache/electron-builder/wine
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
